---
- name: "nginx with varnish caching"
  hosts: localhost
  connection: local
  vars:
    security_group: ash-webserver
    region: ap-south-1
    keypair: ash
    instance_type: t2.micro
    subnet_id: subnet-751a191d
    image: ami-08e76c6a76ebf6433
    mysqlinstance_image: ami-0ebc1ac48dfd14136  
    aws_access_key: AKID*************
    aws_secret_key: lpJywA5XMrKgB******************
    mysql_IP: 172.31.32.10
    webserver_IP: 172.31.40.180
    nginx_port: 8080
    varnish_port: 80
    domain_name: ash.com
    default: default
    mysql_root: ash123
    mysql_database: wordpress
    mysql_user: wordpress-user
    mysql_password: wordpress-user


  tasks:
    - name: Creating a security group
      ec2_group:
        name: "{{ security_group }}"
        description: webservers
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: 0.0.0.0/0  
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Create the web-server Instances
      ec2:
        region: "{{ region }}"
        group: "{{ security_group }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        vpc_subnet_id: "{{ subnet_id }}"
        private_ip: "{{ webserver_IP }}"
        wait: yes
        count: 1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

        instance_tags:
           Name: "webserver"
      register: ec2

    - name: Add web instance to host group webserver
      add_host:
        hostname: webserver
        ansible_host: "{{ item.public_ip }}"
        ansible_port: 22
        ansible_user: "ubuntu"
        ansible_ssh_private_key_file: "/home/ec2-user/ash.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"  
      with_items: "{{ ec2.instances }}" 
    
    - name: Waiting for OpenSSH to open"
      wait_for:
        port: 22
        host: "{{ ec2.instances.0.public_ip }}"
        timeout: 80
        state: started
        delay: 10
        
    - name: Create the DB-server Instances
      ec2:
        region: "{{ region }}"
        group: "{{ security_group }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ mysqlinstance_image }}"
        vpc_subnet_id: "{{ subnet_id }}"
        private_ip: "{{ mysql_IP }}"
        wait: yes
        count: 1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

        instance_tags:
           Name: "DB"
      register: ec2_DB

    - name: Add DB instance to host group
      add_host:
        hostname: dbserver
        ansible_host: "{{ item.public_ip }}" 
        ansible_port: 22
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "/home/ec2-user/ash.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"  
      with_items: "{{ ec2_DB.instances }}" 
    
    - name: Waiting for OpenSSH to open"
      wait_for:
        port: 22
        host: "{{ ec2_DB.instances.0.public_ip }}"
        timeout: 80
        state: started
        delay: 10
        
     
    - name: "nginx installation"
      delegate_to: webserver
      become: yes
      apt: name=nginx state=latest
    
    - name: "changing port"
      delegate_to: webserver
      become: yes
      template:  
        src: default.tmpl
        dest: /etc/nginx/sites-available/default

    - name: "restart nginx"
      delegate_to: webserver
      become: yes
      service:
          name: nginx
          state: reloaded

    - name: varnish installation
      delegate_to: webserver
      become: yes
      apt: name=varnish state=latest update_cache=yes
    
    - name: changing varnish port in /etc/varnish/default.vcl
      delegate_to: webserver
      become: yes
      template:
        src: default.j2
        dest: /etc/varnish/default.vcl
    
    - name: chaning varnish port in /etc/default/varnish
      delegate_to: webserver
      become: yes
      template:
        src: varnish.tmpl
        dest: /etc/default/varnish       
    
    - name: "changing varnish.service port"
      delegate_to: webserver
      become: yes
      template:
        src: varnish.j2 
        dest: /lib/systemd/system/varnish.service                        

    - name: Ensure systemd is reloaded if varnish.service has changed
      delegate_to: webserver
      become: yes
      shell: systemctl daemon-reload 
    
    - name: restart varnish
      delegate_to: webserver
      become: yes
      shell: systemctl restart varnish
    
    - name: "php installation"
      delegate_to: webserver
      become: yes
      apt: name=php,php-mysql,php-fpm state=present
      
    - name: "Mysql - Installation"
      delegate_to: dbserver
      become: yes
      yum:
        name:
          - mariadb-server
          - MySQL-python 
        state: present
    
    - name: "Mysql - Restarting & Enabling"
      delegate_to: dbserver 
      become: yes
      service: 
        name: "{{ item }}"
        state: restarted 
      with_items:
        - mariadb     

    - name: "Mysql - Resetting Root Password"
      delegate_to: dbserver
      become: yes
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{ mysql_root }}"
        host_all: yes
    
        
    - name: "Mysql - creating additional database"
      delegate_to: dbserver
      become: yes
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        name: "{{ mysql_database }}"
        state: present
            
    - name: "Mysql - granting privileges for user to database"
      delegate_to: dbserver
      become: yes
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root }}"
        user: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        state: present
        priv: "{{ mysql_database }}.*:ALL" 
        host: "{{ webserver_IP }}"
    
    - name: " Creating document root"
      delegate_to: webserver
      become: yes
      file:
         path: /var/www/html/{{domain_name}}
         state: directory
         owner: www-data
         group: www-data
         

    - name: " creating virtualhost"
      delegate_to: webserver
      become: yes
      template:  
        src: nginx-sites.j2
        dest: /etc/nginx/sites-available/{{domain_name}}
    
    - name: "create file link"
      delegate_to: webserver
      become: yes
      file:
        src: /etc/nginx/sites-available/{{domain_name}}
        dest: /etc/nginx/sites-enabled/{{domain_name}}
        state: link
        force: yes        

    - name: "download wordpress tar file"
      delegate_to: webserver
      become: yes
      get_url:
         url: https://wordpress.org/wordpress-4.9.2.tar.gz
         dest: /tmp/wordpress.tar.gz  

    - name: "Extract files"
      delegate_to: webserver
      become: yes
      unarchive:
           src: /tmp/wordpress.tar.gz
           dest: /tmp
           remote_src: yes

    - name: "Copying wordpress contents to document root"
      delegate_to: webserver
      become: yes
      shell: "cp -r /tmp/wordpress/* /var/www/html/{{domain_name}}"

    - name: "Wordpress - file ownership "
      delegate_to: webserver
      become: yes
      shell: " chown -R www-data:www-data /var/www/html/{{domain_name}}"   

    - name: "Wordpress- Creating wp-config.php"
      delegate_to: webserver
      become: yes
      template:
          src: wp-config.j2
          dest: /var/www/html/{{ domain_name }}/wp-config.php    
  

    - name: "Deleting files from /tmp folder "
      delegate_to: webserver
      become: yes
      file:
         path: "{{ item }}"        
         state: absent
      with_items:
          - /tmp/wordpress.tar.gz
          - /tmp/wordpress
 
    - name: "restart nginx"
      delegate_to: webserver
      become: yes
      service:
          name: nginx
          state: reloaded
    
    - name: "restart mysql"
      delegate_to: dbserver
      become: yes
      service:
          name: mariadb
          state: restarted 
