---
- name: "varnish"
  hosts: localhost
  connection: local
  vars:
    security_group: ash-webserver
    region: ap-south-1
    keypair: ash
    instance_type: t2.micro
    subnet_id: subnet-751a191d
    image: ami-0ebc1ac48dfd14136
    aws_access_key: AKIAW4AVUN6KLJBN3D72
    aws_secret_key: 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
    
    
  tasks:
    - name: Creating a security group
      ec2_group:
        name: "{{ security_group }}"
        description: webservers
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    
    - name: Create the web-server Instances
      ec2:
        region: "{{ region }}"
        group: "{{ security_group }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        vpc_subnet_id: 
        wait: yes
        count: 1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        
        instance_tags:
           Name: "webserver"
      register: ec2
      
    - debug:
        var: item.private_ip
      with_items: "{{ ec2.instances }}" 
   
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: webserver
      with_items: "{{ ec2.instances }}"

     
